### ISSUE TITLE
Adding Creational issue

### ISSUE THREAD

**Issue by nk932714** [jpillora/node-torrent-cloud#18]
hi jpillora , How to define mega variable in codeanywhere   (dot)com

**Comment by nk932714** [comment]
anyone knows how to solve this problem 
When i added manually mega username and password in config file is says no backend match environmental variables missing for : aws.js, mega.js

**Comment by nk932714** [comment]
please check this error [click](https://ibb.co/iVOk75)

**Comment by rakshans1** [comment]
@nk932714 please recreate error from backend

**Comment by nk932714** [comment]
do i need to chnage oter files also ( i changed only cofig.json and add my mega account username and pass )

Example - App.js
		"AWS_BUCKET": { "required": false },
		"AWS_REGION": { "required": false },
		"AWS_ACCESS_KEY": { "required": false },
		"AWS_SECRET_KEY": { "required": false },
		**"MEGA_EMAIL": { "required": true },** changed it to true
		**"MEGA_PASS": { "required": true }** changed it to true


do i need to change something else too
