### ISSUE TITLE
strucked on this page. Keep showing loading

### ISSUE THREAD

**Issue by nk932714** [jpillora/node-torrent-cloud#22]
![image](https://user-images.githubusercontent.com/29853208/29451333-ecc9f274-841f-11e7-9c41-12aa6479d521.png)

How to fix this please help

**Comment by bharadwajpro** [comment]
Where are you deploying? Add a torrent which has more seeders.

**Comment by nk932714** [comment]
I was deploying on codeanywhere.com and also tried on openshift. At least I have tried 50-50 torrents on both sites wich have top seeds from 1337 and piratebay but none works :(

**Comment by nk932714** [comment]
thanks @bharadwajpro Got the issue they were blocking bitorrent traffic
