### ISSUE TITLE
correct proxy_pass for nginx

### ISSUE THREAD

**Issue by saveyour** [jpillora/node-torrent-cloud#3]
it seems to work with the below settings: (some of them may be redundant/not applicable)

        location /api/ { 
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Real-IP       $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_pass_header Server;
                proxy_set_header Host $host;
                proxy_buffering off;
                proxy_pass http://nodetorrent:8080/api/;
        }

        location / {
        	proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header Connection $connection_upgrade;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_set_header Host $host;
	        proxy_pass_header Server;
	        proxy_set_header Host $host;
	        proxy_buffering off;
               proxy_pass http://nodetorrent:8080/;
	}

**Comment by jpillora** [comment]
thanks
