### ISSUE TITLE
Azure Web App problem

### ISSUE THREAD

**Issue by RonCan** [jpillora/node-torrent-cloud#4]
When I try to run this project locally and on heroku it runs perfectly fine but when I deploy it on Azure the Websocket connection keeps connecting and disconnecting in a matter of milli-seconds. I have turned the WebSockets support on. Do you have any ideas?

**Comment by jpillora** [comment]
My little experience with azure proved to be quite frustrating. All I can
say is avoid them and go with anyone else, AWS are good.

**Comment by RonCan** [comment]
Thanks I'll try to change the platform. The torrent downloading speeds are frustrating too(hardly 300-400 on top torrents) both on heroku(free, makes sense) and azure(premium,standard, doesn't make sense). Whereas there are services like put.io which provide mind-boggling(5MB+) speeds. Do you have any thoughts+suggestions?

**Comment by jpillora** [comment]
I've seen 5-8MB on Heroku. If you're using AWS S3, it's important to choose a region close to where torrent cloud is hosted.

I'm in the process of writing version 2 in Go. It should have better performance and more features, like optionally save to disk, which would simplify and speed the storage pipeline.

**Comment by jpillora** [comment]
Closing this, though I'll note that version 2 has much better performance https://github.com/jpillora/cloud-torrent (see screenshot)
