### ISSUE TITLE
Download gets stuck and doesnt respond

### ISSUE THREAD

**Issue by asfand687** [jpillora/node-torrent-cloud#6]
hey,
      i've been using torrent-cloud for a few days now and i must admire what you have done. It is a very cool thing. i have been encountering an issue lately that while downloading a torrent the downloading speed reduces to zero b/s and after that it doesnt resume or increase the speed, it sort of freezes. Is there any way to mitigate this nuisance?

**Comment by jpillora** [comment]
Could be a [heroku](https://github.com/jpillora/cloud-torrent/wiki/Heroku) issue? otherwise, if you don't mind saving files to disk, could swap to https://github.com/jpillora/cloud-torrent since I don't maintain this version anymore

**Comment by asfand687** [comment]
thanks man you are awesome.

**Comment by asfand687** [comment]
hello Jaime,
                can you tell me how can i deploy this app to cloud 66 or
any other cloud service provider? Thanks

**Comment by jpillora** [comment]
Deploying to heroku is in the README, otherwise, best advice I can give is to google "deploy node application on digital ocean"
